[[keyboard.bindings]]
action = "Paste"
key = "Insert"
mode = "~Vi"
mods = "Shift"

[[keyboard.bindings]]
action = "Copy"
key = "Insert"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0013"
key = "S"
mods = "Command"

[cursor.style]
shape = "Block"

[font]
size = 16.0

[font.normal]
family = "Ubuntu Mono"

[window]
decorations_theme_variant = "Dark"
opacity = 1.0
startup_mode = "Maximized"

[keyboard]


