[cursor.style]
shape = "Block"

[font]
size = 12.0

[font.normal]
family = "UbuntuMono Nerd Font"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mode = "~Vi"
mods = "Alt"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[shell]
program = "wsl -d Ubuntu"

[window]
decorations_theme_variant = "Dark"
opacity = 1.0
startup_mode = "Maximized"
