{% set version = "5.4.1" %}

package:
  name: gradle
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://github.com/gradle/gradle.git

build:
  number: 0

requirements:

test:
  commands:
      #- nvim --version


about:
  home: https://gradle.org/
  license: Free software (Apache 2.0)
  summary: Adaptable, fast automation for all https://gradle.org

extra:
  recipe-maintainers:
    - daizeng1984
