{% set version = "16.02" %}

package:
  name: p7zip
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/jbdemonte/p7zip.git

build:
  number: 0

requirements:
  build:
    - clangdev

test:
  requirements:
  commands:
      #- make test


about:
  home: http://p7zip.sourceforge.net/
  license: GNU LGPL
  summary: p7zip is a port of 7za.exe for POSIX systems like Unix (Linux, Solaris, OpenBSD, FreeBSD, Cygwin, AIX, ...), MacOS X and also for BeOS and Amiga.

extra:
  recipe-maintainers:
    - daizeng1984
