{% set version = "0.3.2" %}

package:
  name: nvim
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://github.com/neovim/neovim.git

build:
  number: 0

requirements:
  build:
    - clangdev
    - ninja
    - cmake
    - gettext 
    - pkg-config
    - libtool
    - autoconf
    - automake
    - unzip
  host:
    - libiconv
  run:
    - libiconv

test:
  requirements:
    - libiconv 
  commands:
      #- nvim --version


about:
  home: https://salt.bountysource.com/teams/neovim
  license: Free software (Apache)
  summary: Vim-fork focused on extensibility and usability https://salt.bountysource.com/teams/neovim

extra:
  recipe-maintainers:
    - daizeng1984
