{% set name = "nvim" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: v{{ version }}.tar.gz
  url: https://github.com/neovim/neovim/archive/v{{ version }}.tar.gz
  sha256: dd882c21a52e5999f656cae3f336b5fc702d52addd4d9b5cd3dc39cfff35e864

build:
  number: 0
  skip: True  # [win]

# linux install apt install gcc-multilib for lua deps compiling
requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - automake
    - ninja
    - autoconf
    - libtool
    - automake
    - gettext

  host:
    - gettext
    - libiconv
  run:
    - gettext
    - libiconv

test:
  commands:
    - test -f $PREFIX/bin/nvim

about:
  home: https://neovim.io/
  license: Apache 2.0/ Vim License
  summary: Vim-fork focused on extensibility and usability https://salt.bountysource.com/teams/neovim
  description: Vim is a powerful text editor with a big community that is constantly growing. Even though the editor is about two decades old, people still extend and want to improve it, mostly using Vimscript or one of the supported scripting languages.
  doc_url: https://neovim.io/doc/
  dev_url: https://github.com/neovim/neovim

extra:
  recipe-maintainers:
    - daizeng1984
