{% set version = "0.4.4" %}

package:
  name: nvim
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://github.com/neovim/neovim.git

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - libiconv
  run:
    - libiconv

test:
  requirements:
  commands:
    - test -f $PREFIX/bin/nvim


about:
  home: https://salt.bountysource.com/teams/neovim
  license: Free software (Apache)
  summary: Vim-fork focused on extensibility and usability https://salt.bountysource.com/teams/neovim

extra:
  recipe-maintainers:
    - daizeng1984
