{% set name = "nvim" %}
{% set version = "0.4.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://github.com/neovim/neovim.git
  patches:
    - fix-empty-command.patch

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - pkg-config
    - automake
    - autoconf
    - automake
    - gettext

  host:
    - libiconv
  run:
    - libiconv

test:
  commands:
    - test -f $PREFIX/bin/nvim


about:
  home: https://neovim.io/
  license: Apache 2.0/ Vim License
  summary: Vim-fork focused on extensibility and usability https://salt.bountysource.com/teams/neovim
  description: Vim is a powerful text editor with a big community that is constantly growing. Even though the editor is about two decades old, people still extend and want to improve it, mostly using Vimscript or one of the supported scripting languages.
  doc_url: https://neovim.io/doc/
  dev_url: https://github.com/neovim/neovim

extra:
  recipe-maintainers:
    - daizeng1984
