{% set version = "4.6.0" %}

package:
  name: git-extras
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/tj/git-extras.git

build:
  number: 0

requirements:
  build:
  host:
  run:

test:
  requirements:
  commands:


about:
  home: https://github.com/tj/git-extras.git
  license: MIT
  summary: GIT utilities -- repo summary, repl, changelog population, author commit percentages and more

extra:
  recipe-maintainers:
    - daizeng1984
