{% set version = "0.20190314.1" %}

package:
  name: ccls
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/MaskRay/ccls.git

build:
  number: 0

requirements:
  build:
    - clangdev
    - llvmdev
    - lld
    - cmake

test:
  requirements:
  commands:


about:
  home: https://github.com/MaskRay/ccls
  license: Free software (Apache-2.0)
  summary: C/C++/ObjC language server supporting cross references, hierarchies, completion and semantic highlighting

extra:
  recipe-maintainers:
    - daizeng1984
