{% set version = "7.2.0" %}

package:
  name: fd-find
  version: {{ version }}

source:
  git_rev: v{{ version }}
  git_url: https://github.com/sharkdp/fd.git

build:
  number: 0

requirements:
  build:
    - rust
  host:
  run:

test:
  requirements:
  commands:


about:
  home: https://github.com/sharkdp/fd
  license: MIT/Apache
  summary: A simple, fast and user-friendly alternative to 'find'<Paste>

extra:
  recipe-maintainers:
    - daizeng1984
