# Run it with x window
# sudo docker run -ti --rm --device /dev/snd --group-add audio -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix ubuntu-fceux
FROM ufoym/deepo
RUN apt-get install -y fceux
RUN pip3 install gym
