fun AsciiEmoji()
    " steal from http://asciimoji.com/
    " Just for fun ٩(^‿^)۶
    let s:menus = {}

    let s:menus.emoji = {
                \ 'description': 'Ascii Emoji'
                \ }

    let s:menus.emoji.command_candidates = [
                \ ['bear', 'normal iʕ·͡ᴥ·ʔ'],
                \ ['acid', 'normal i⊂(◉‿◉)つ'],
                \ ['afraid', 'normal i(ㆆ _ ㆆ)'],
                \ ['angel', 'normal i☜(⌒▽⌒)☞'],
                \ ['angry', 'normal i•`_´•'],
                \ ['arrowhead', 'normal i⤜(ⱺ ʖ̯ⱺ)⤏'],
                \ ['apple', 'normal i'],
                \ ['ass', 'normal i(‿|‿)'],
                \ ['awkward', 'normal i•͡˘㇁•͡˘'],
                \ ['bat', 'normal i/|\ ^._.^ /|\'],
                \ ['bearflip', 'normal iʕノ•ᴥ•ʔノ ︵ ┻━┻'],
                \ ['bearhug', 'normal iʕっ•ᴥ•ʔっ'],
                \ ['since', 'normal i∵'],
                \ ['bigheart', 'normal i❤'],
                \ ['blackeye', 'normal i0__#'],
                \ ['blubby', 'normal i( 0 _ 0 )'],
                \ ['blush', 'normal i(˵ ͡° ͜ʖ ͡°˵)'],
                \ ['007', 'normal i┌( ͝° ͜ʖ͡°)=ε/̵͇̿̿/’̿’̿ ̿'],
                \ ['boobs', 'normal i( . Y . )'],
                \ ['bored', 'normal i(-_-)'],
                \ ['bribe', 'normal i( •͡˘ _•͡˘)ノð'],
                \ ['bubbles', 'normal i( ˘ ³˘)ノ°ﾟº❍｡'],
                \ ['butterfly', 'normal iƸӜƷ'],
                \ ['cat', 'normal i(= ФェФ=)'],
                \ ['catlenny', 'normal i( ͡° ᴥ ͡°)'],
                \ ['check', 'normal i✓'],
                \ ['chubby', 'normal i╭(ʘ̆~◞౪◟~ʘ̆)╮'],
                \ ['claro', 'normal i(͡ ° ͜ʖ ͡ °)'],
                \ ['gang', 'normal iヽ༼ ຈل͜ຈ༼ ▀̿̿Ĺ̯̿̿▀̿ ̿༽Ɵ͆ل͜Ɵ͆ ༽ﾉ'],
                \ ['cloud', 'normal i☁'],
                \ ['club', 'normal i♣'],
                \ ['cuppa', 'normal ic[_]'],
                \ ['command', 'normal i⌘'],
                \ ['csi', 'normal i(•_•) ( •_•)>⌐■-■ (⌐■_■)'],
                \ ['c', 'normal i©'],
                \ ['creep', 'normal iԅ(≖‿≖ԅ)'],
                \ ['creepcute', 'normal iƪ(ړײ)‎ƪ​​'],
                \ ['crim3s', 'normal i( ✜︵✜ )'],
                \ ['cross', 'normal i†'],
                \ ['cry', 'normal i(╥﹏╥)'],
                \ ['crywave', 'normal i( ╥﹏╥) ノシ'],
                \ ['cute', 'normal i(｡◕‿‿◕｡)'],
                \ ['d1', 'normal i⚀'],
                \ ['d2', 'normal i⚁'],
                \ ['d3', 'normal i⚂'],
                \ ['d4', 'normal i⚃'],
                \ ['d5', 'normal i⚄'],
                \ ['d6', 'normal i⚅'],
                \ ['damnyou', 'normal i(ᕗ ͠° ਊ ͠° )ᕗ'],
                \ ['dance', 'normal iᕕ(⌐■_■)ᕗ ♪♬'],
                \ ['dead', 'normal ix⸑x'],
                \ ['dwi', 'normal i(⌐■_■)'],
                \ ['delta', 'normal iΔ'],
                \ ['depressed', 'normal i(︶︹︶)'],
                \ ['derp', 'normal i☉ ‿ ⚆'],
                \ ['diamond', 'normal i♦'],
                \ ['dog', 'normal i(◕ᴥ◕ʋ)'],
                \ ['dollar', 'normal i$'],
                \ ['$', 'normal i	[̲̅$̲̅(̲̅ιο̲̅̅)̲̅$̲̅]'],
                \ ['dong', 'normal i(̿▀̿ ̿Ĺ̯̿̿▀̿ ̿)̄'],
                \ ['donger', 'normal iヽ༼ຈل͜ຈ༽ﾉ'],
                \ ['dontcare', 'normal i╭∩╮（︶︿︶）╭∩╮'],
                \ ['dontwant', 'normal iヽ(｀Д´)ﾉ'],
                \ ['dope', 'normal i<(^_^)>'],
                \ ['<<', 'normal i«'],
                \ ['>>', 'normal i»'],
                \ ['doubleflat', 'normal i𝄫'],
                \ ['doublesharp', 'normal i𝄪'],
                \ ['doubletableflip', 'normal i┻━┻ ︵ヽ(`Д´)ﾉ︵ ┻━┻'],
                \ ['down', 'normal i↓'],
                \ ['duckface', 'normal i(・3・)'],
                \ ['duel', 'normal iᕕ(╭ರ╭ ͟ʖ╮•́)⊃¤=(————-'],
                \ ['duh', 'normal i(≧︿≦)'],
                \ ['dunno', 'normal i¯\(°_o)/¯'],
                \ ['ebola', 'normal iᴇʙᴏʟᴀ'],
                \ ['...', 'normal i…'],
                \ ['--', 'normal i–'],
                \ ['emptystar', 'normal i☆'],
                \ ['t2', 'normal i△'],
                \ ['endure', 'normal i(҂◡_◡) ᕤ'],
                \ ['letter', 'normal i✉︎'],
                \ ['epsilon', 'normal iɛ'],
                \ ['euro', 'normal i€'],
                \ ['evil', 'normal iψ(｀∇´)ψ'],
                \ ['evillenny', 'normal i(͠≖ ͜ʖ͠≖)'],
                \ ['execution', 'normal i(⌐■_■)︻╦╤─ (╥﹏╥)'],
                \ ['facebook', 'normal i(╯°□°)╯︵ ʞooqǝɔɐɟ'],
                \ ['facepalm', 'normal i(－‸ლ)'],
                \ ['fancytext', 'normal i	вєωαяє, ι αм ƒαη¢у!'],
                \ ['fart', 'normal i(ˆ⺫ˆ๑)<3'],
                \ ['fight', 'normal i(ง •̀_•́)ง'],
                \ ['finn', 'normal i| (• ◡•)|'],
                \ ['fish', 'normal i<"(((<3'],
                \ ['five', 'normal i卌'],
                \ ['5/8', 'normal i⅝'],
                \ ['bemolle', 'normal i♭'],
                \ ['flexing', 'normal iᕙ(`▽´)ᕗ'],
                \ ['fliptext', 'normal i	ǝןqɐʇ ɐ ǝʞıן ǝɯ dıןɟ'],
                \ ['fliptexttable', 'normal i	(ノ ゜Д゜)ノ ︵ ǝןqɐʇ ɐ ǝʞıן ʇxǝʇ dıןɟ'],
                \ ['heavytable', 'normal i┬─┬﻿ ︵ /(.□. \）'],
                \ ['flor', 'normal i(✿◠‿◠)'],
                \ ['f', 'normal i✿'],
                \ ['fly', 'normal i─=≡Σ((( つ◕ل͜◕)つ'],
                \ ['friendflip', 'normal i(╯°□°)╯︵ ┻━┻ ︵ ╯(°□° ╯)'],
                \ ['frown', 'normal i(ღ˘⌣˘ღ)'],
                \ ['gtfo', 'normal i୧༼ಠ益ಠ╭∩╮༽'],
                \ ['fu', 'normal i┌П┐(ಠ_ಠ)'],
                \ ['monocle', 'normal iಠ_ರೃ'],
                \ ['ghast', 'normal i= _ ='],
                \ ['ghost', 'normal i༼ つ ❍_❍ ༽つ'],
                \ ['present', 'normal i(´・ω・)っ由'],
                \ ['gimme', 'normal i༼ つ ◕_◕ ༽つ'],
                \ ['glitter', 'normal i(*・‿・)ノ⌒*:･ﾟ✧'],
                \ ['glasses', 'normal i(⌐ ͡■ ͜ʖ ͡■)'],
                \ ['glassesoff', 'normal i( ͡° ͜ʖ ͡°)ﾉ⌐■-■'],
                \ ['glitterderp', 'normal i(ﾉ☉ヮ⚆)ﾉ ⌒*:･ﾟ✧'],
                \ ['gloomy', 'normal i(_゜_゜_)'],
                \ ['goatse', 'normal i(з๏ε)'],
                \ ['gotit', 'normal i(☞ﾟ∀ﾟ)☞'],
                \ ['greetings', 'normal i( ´◔ ω◔`) ノシ'],
                \ ['mg', 'normal i︻╦╤─'],
                \ ['hadouken', 'normal i༼つಠ益ಠ༽つ ─=≡ΣO))'],
                \ ['hs', 'normal i☭'],
                \ ['hl', 'normal i☜'],
                \ ['hr', 'normal i☞'],
                \ ['haha', 'normal i٩(^‿^)۶'],
                \ ['happy', 'normal i٩( ๑╹ ꇴ╹)۶'],
                \ ['happygarry', 'normal iᕕ( ᐛ )ᕗ'],
                \ ['heart', 'normal i♥'],
                \ ['bye', 'normal i(ʘ‿ʘ)╯'],
                \ ['highfive', 'normal i._.)/\(._.'],
                \ ['hitting', 'normal i( ｀皿´)｡ﾐ/'],
                \ ['hugs', 'normal i(づ｡◕‿‿◕｡)づ'],
                \ ['iknowright', 'normal i┐｜･ิω･ิ#｜┌'],
                \ ['illuminati', 'normal i୧(▲ᴗ▲)ノ'],
                \ ['inf', 'normal i∞'],
                \ ['inlove', 'normal i(っ´ω`c)♡'],
                \ ['int', 'normal i∫'],
                \ ['internet', 'normal iଘ(੭*ˊᵕˋ)੭* ̀ˋ ɪɴᴛᴇʀɴᴇᴛ'],
                \ ['interrobang', 'normal i‽'],
                \ ['jake', 'normal i(❍ᴥ❍ʋ)'],
                \ ['kawaii', 'normal i≧◡≦'],
                \ ['keen', 'normal i┬┴┬┴┤Ɵ͆ل͜Ɵ͆ ༽ﾉ'],
                \ ['kiahh', 'normal i~\(≧▽≦)/~'],
                \ ['kiss', 'normal i(づ ￣ ³￣)づ'],
                \ ['kyubey', 'normal i／人◕ ‿‿ ◕人＼'],
                \ ['lambda', 'normal iλ'],
                \ ['lazy', 'normal i_(:3」∠)_'],
                \ ['arrowleft', 'normal i←'],
                \ ['lenny', 'normal i( ͡° ͜ʖ ͡°)'],
                \ ['lennybill', 'normal i[̲̅$̲̅(̲̅ ͡° ͜ʖ ͡°̲̅)̲̅$̲̅]'],
                \ ['lennyfight', 'normal i(ง ͠° ͟ʖ ͡°)ง'],
                \ ['lennyflip', 'normal i(ノ ͡° ͜ʖ ͡°ノ) ︵ ( ͜。 ͡ʖ ͜。)'],
                \ ['lennygang', 'normal i( ͡°( ͡° ͜ʖ( ͡° ͜ʖ ͡°)ʖ ͡°) ͡°)'],
                \ ['lennyshrug', 'normal i¯\_( ͡° ͜ʖ ͡°)_/¯'],
                \ ['lennysir', 'normal i( ಠ ͜ʖ ರೃ)'],
                \ ['lennystalker', 'normal i┬┴┬┴┤( ͡° ͜ʖ├┬┴┬┴'],
                \ ['lennystrong', 'normal iᕦ( ͡° ͜ʖ ͡°)ᕤ'],
                \ ['lennywizard', 'normal i╰( ͡° ͜ʖ ͡° )つ──☆*:・ﾟ'],
                \ ['loading', 'normal i	███▒▒▒▒▒▒▒'],
                \ ['lol', 'normal iL(° O °L)'],
                \ ['look', 'normal i(ಡ_ಡ)☞'],
                \ ['love', 'normal i♥‿♥'],
                \ ['lovebear', 'normal iʕ♥ᴥ♥ʔ'],
                \ ['lumpy', 'normal i꒰ ꒡⌓꒡꒱'],
                \ ['luv', 'normal i-`ღ´-'],
                \ ['magic', 'normal iヽ(｀Д´)⊃━☆ﾟ. * ･ ｡ﾟ,'],
                \ ['magicflip', 'normal i(/¯◡ ‿ ◡)/¯ ~ ┻━┻'],
                \ ['meep', 'normal i\(°^°)/'],
                \ ['meh', 'normal iಠ_ಠ'],
                \ ['mistyeyes', 'normal iಡ_ಡ'],
                \ ['monster', 'normal i༼ ༎ຶ ෴ ༎ຶ༽'],
                \ ['natural', 'normal i♮'],
                \ ['inject', 'normal i┌(◉ ͜ʖ◉)つ┣▇▇▇═──'],
                \ ['nice', 'normal i( ͡° ͜ °)'],
                \ ['no', 'normal i→_←'],
                \ ['noclue', 'normal i／人◕ __ ◕人＼'],
                \ ['delicious', 'normal i(っˆڡˆς)'],
                \ ['sing', 'normal i♫'],
                \ ['nukular', 'normal i☢'],
                \ ['nyan', 'normal i~=[,,_,,]:3'],
                \ ['nyeh', 'normal i@^@'],
                \ ['ohshit', 'normal i( º﹃º )'],
                \ ['omg', 'normal i◕_◕'],
                \ ['1/8', 'normal i⅛'],
                \ ['1/4', 'normal i¼'],
                \ ['1/2', 'normal i½'],
                \ ['1/3', 'normal i⅓'],
                \ ['option', 'normal i⌥'],
                \ ['orly', 'normal i(눈_눈)'],
                \ ['ou', 'normal i(◞థ౪థ)ᴖ'],
                \ ['victory', 'normal i✌(-‿-)✌'],
                \ ['pear', 'normal i(__>-'],
                \ ['pi', 'normal iπ'],
                \ ['pingpong', 'normal i( •_•)O*¯`·.¸.·´¯`°Q(•_• )'],
                \ ['plain', 'normal i._.'],
                \ ['pleased', 'normal i(˶‾᷄ ⁻̫ ‾᷅˵)'],
                \ ['point', 'normal i(☞ﾟヮﾟ)☞'],
                \ ['pooh', 'normal iʕ •́؈•̀)'],
                \ ['pound', 'normal i£'],
                \ ['praise', 'normal i(☝ ՞ਊ ՞)☝'],
                \ ['punch', 'normal iO=('-'Q)'],
                \ ['mad', 'normal it(ಠ益ಠt)'],
                \ ['rageflip', 'normal i(ノಠ益ಠ)ノ彡┻━┻'],
                \ ['rainbowcat', 'normal i(=^･ｪ･^=))ﾉ彡☆'],
                \ ['really', 'normal iò_ô'],
                \ ['r', 'normal i®'],
                \ ['->', 'normal i→'],
                \ ['riot', 'normal i୧༼ಠ益ಠ༽୨'],
                \ ['rolldice', 'normal i	⚅'],
                \ ['rolleyes', 'normal i(◔_◔)'],
                \ ['rose', 'normal i✿ڿڰۣ—'],
                \ ['run', 'normal i(╯°□°)╯'],
                \ ['sad', 'normal iε(´סּ︵סּ`)з'],
                \ ['saddonger', 'normal iヽ༼ຈʖ̯ຈ༽ﾉ'],
                \ ['sadlenny', 'normal i( ͡° ʖ̯ ͡°)'],
                \ ['7/8', 'normal i⅞'],
                \ ['diesis', 'normal i♯'],
                \ ['shout', 'normal i╚(•⌂•)╝'],
                \ ['shrug', 'normal i¯\_(ツ)_/¯'],
                \ ['shy', 'normal i=^_^='],
                \ ['sum', 'normal iΣ'],
                \ ['skull', 'normal i☠'],
                \ ['smile', 'normal iツ'],
                \ ['smiley', 'normal i☺︎'],
                \ ['smirk', 'normal i¬‿¬'],
                \ ['snowman', 'normal i☃'],
                \ ['sob', 'normal i(;´༎ຶД༎ຶ`)'],
                \ ['spade', 'normal i♠'],
                \ ['sqrt', 'normal i√'],
                \ ['squid', 'normal i<コ:彡'],
                \ ['star', 'normal i★'],
                \ ['strong', 'normal iᕙ(⇀‸↼‶)ᕗ'],
                \ ['suicide', 'normal iε/̵͇̿̿/’̿’̿ ̿(◡︵◡)'],
                \ ['sum', 'normal i∑'],
                \ ['sun', 'normal i☀'],
                \ ['surprised', 'normal i(๑•́ ヮ •̀๑)'],
                \ ['surrender', 'normal i\_(-_-)_/'],
                \ ['stalker', 'normal i┬┴┬┴┤(･_├┬┴┬┴'],
                \ ['swag', 'normal i(̿▀̿‿ ̿▀̿ ̿)'],
                \ ['sword', 'normal io()xxxx[{::::::::::::::::::>'],
                \ ['tabledown', 'normal i┬─┬﻿ ノ( ゜-゜ノ)'],
                \ ['tableflip', 'normal i(ノ ゜Д゜)ノ ︵ ┻━┻'],
                \ ['tau', 'normal iτ'],
                \ ['tears', 'normal i(ಥ﹏ಥ)'],
                \ ['terrorist', 'normal i୧༼ಠ益ಠ༽︻╦╤─'],
                \ ['thankyou', 'normal i\(^-^)/'],
                \ ['so', 'normal i⸫'],
                \ ['3/8', 'normal i⅜'],
                \ ['tiefighter', 'normal i|=-(¤)-=|'],
                \ ['tired', 'normal i(=____=)'],
                \ ['toldyou', 'normal i☜(꒡⌓꒡)'],
                \ ['toogood', 'normal iᕦ(òᴥó)ᕥ'],
                \ ['tm', 'normal i™'],
                \ ['triangle', 'normal i▲'],
                \ ['2/3', 'normal i⅔'],
                \ ['unflip', 'normal i┬──┬ ノ(ò_óノ)'],
                \ ['up', 'normal i↑'],
                \ ['victory', 'normal i(๑•̀ㅂ•́)ง✧'],
                \ ['wat', 'normal i(ÒДÓױ)'],
                \ ['wave', 'normal i( * ^ *) ノシ'],
                \ ['whaa', 'normal iÖ'],
                \ ['whistle', 'normal i(っ^з^)♪♬'],
                \ ['whoa', 'normal i(°o•)'],
                \ ['why', 'normal iლ(`◉◞౪◟◉‵ლ)'],
                \ ['witchtext', 'normal i	WHΣИ $HΛLL WΣ †HЯΣΣ MΣΣ† ΛGΛ|И?'],
                \ ['woo', 'normal i＼(＾O＾)／'],
                \ ['wtf', 'normal i(⊙＿⊙`)'],
                \ ['wut', 'normal i⊙ω⊙'],
                \ ['yay', 'normal i\( ﾟヮﾟ)/'],
                \ ['yes', 'normal i(•̀ᴗ•́)و ̑̑'],
                \ ['yen', 'normal i¥'],
                \ ['yy', 'normal i☯'],
                \ ['yolo', 'normal iYᵒᵘ Oᶰˡʸ Lᶤᵛᵉ Oᶰᶜᵉ'],
                \ ['ukids', 'normal iლ༼>╭ ͟ʖ╮<༽ლ'],
                \ ['yuno', 'normal i(屮ﾟДﾟ)屮 Y U NO'],
                \ ['omm', 'normal i⊹╰(⌣ʟ⌣)╯⊹'],
                \ ['zoidberg', 'normal i(V) (°,,,,°) (V)'],
                \ ['zombie', 'normal i[¬º-°]¬'],
                \ ]
    call denite#custom#var('menu', 'menus', s:menus)
    
endf

